var annotated_dup =
[
    [ "meshviewer", null, [
      [ "Mesh", "classmeshviewer_1_1Mesh.html", "classmeshviewer_1_1Mesh" ]
    ] ],
    [ "Camera", "classCamera.html", "classCamera" ],
    [ "CentroidInitMethod", "classCentroidInitMethod.html", "classCentroidInitMethod" ],
    [ "CentroidPoint", "classCentroidPoint.html", "classCentroidPoint" ],
    [ "CSVUtils", "classCSVUtils.html", null ],
    [ "ElbowMethod", "classElbowMethod.html", "classElbowMethod" ],
    [ "Enums", "classEnums.html", null ],
    [ "EuclideanMetric", "classEuclideanMetric.html", "classEuclideanMetric" ],
    [ "Face", "structFace.html", "structFace" ],
    [ "GeodesicHeatMetric", "classGeodesicHeatMetric.html", "classGeodesicHeatMetric" ],
    [ "GeodesicMetric", "classGeodesicMetric.html", "classGeodesicMetric" ],
    [ "HasWgtCent", "classHasWgtCent.html", "classHasWgtCent" ],
    [ "KDE", "classKDE.html", "classKDE" ],
    [ "KDE3D", "classKDE3D.html", "classKDE3D" ],
    [ "KDEBase", "classKDEBase.html", "classKDEBase" ],
    [ "KDEMethod", "classKDEMethod.html", "classKDEMethod" ],
    [ "KdNode", "classKdNode.html", "classKdNode" ],
    [ "KdTree", "classKdTree.html", "classKdTree" ],
    [ "Kernel", "classKernel.html", null ],
    [ "Kinit", "classKinit.html", "classKinit" ],
    [ "KMeans", "classKMeans.html", "classKMeans" ],
    [ "Material", "classMaterial.html", "classMaterial" ],
    [ "Mesh", "classMesh.html", "classMesh" ],
    [ "MeshSegmentation", "classMeshSegmentation.html", "classMeshSegmentation" ],
    [ "Metric", "classMetric.html", "classMetric" ],
    [ "Model", "classModel.html", "classModel" ],
    [ "ModelRotationCamera", "classModelRotationCamera.html", "classModelRotationCamera" ],
    [ "MostDistanceClass", "classMostDistanceClass.html", "classMostDistanceClass" ],
    [ "PhongMaterial", "classPhongMaterial.html", "classPhongMaterial" ],
    [ "Point", "classPoint.html", "classPoint" ],
    [ "RandomCentroidInit", "classRandomCentroidInit.html", "classRandomCentroidInit" ],
    [ "Render", "classRender.html", "classRender" ],
    [ "Shader", "classShader.html", "classShader" ],
    [ "ShaderProgram", "classShaderProgram.html", "classShaderProgram" ],
    [ "SilhouetteMethod", "classSilhouetteMethod.html", "classSilhouetteMethod" ],
    [ "Texture2D", "classTexture2D.html", "classTexture2D" ]
];